name: Publish

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Publish to JSR
        run: deno publish
